# In this file, we are mentioning all columns which we are expecting from fetched data with their data types (Data Validation Part)

columns:
  - id: int 
  - Gender: category
  - Age: int
  - Driving_License: int
  - Region_Code: float
  - Previously_Insured: int
  - Vehicle_Age: category
  - Vehicle_Damage: category
  - Annual_Premium: float
  - Policy_Sales_Channel: float
  - Vintage: int
  - Response: int

# Numerical columns we expect
numerical_columns:
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  - Response

# Categorical columns we expect
categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage

# Drop columns
drop_columns: _id 

# Standard scaling columns (Data transformation)
num_features:
  - Age
  - Vintage

# For min-max scaling
mm_columns:
  - Annual_Premium